"""empty message

Revision ID: dd813db86462
Revises: 
Create Date: 2023-07-06 13:52:27.741174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd813db86462'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reptiles',
    sa.Column('reptile_id', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.String(length=255), nullable=True),
    sa.Column('information', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('reptile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reptiles')
    # ### end Alembic commands ###
